# CHANGE THIS ONE IF TIMER STARTED LATE, SAVE, THEN REFRESH
elapsed_min: 0

countdown_min: 105
zero_message: "FINISH THIS END. DO NOT START ANOTHER."
max_min: 120
max_message: "STOP NOW. ENDS IN PROGRESS DO NOT COUNT."